In [ ]:
import numpy as np
import pandas as pd
energy_data = pd.read_csv('energy_consumption.csv')

In [ ]:
# Display the number of null values in each column
null_values = energy_data.isna().sum()
print("Number of null values in each column:")
print(null_values)

# Replace null values with the mean of only numeric columns
numeric_cols = energy_data.select_dtypes(include='number').columns
energy_data[numeric_cols] = energy_data[numeric_cols].fillna(energy_data[numeric_cols].mean())

# Display the updated DataFrame
print("\nData after replacing null values with the mean:")
print(energy_data.head())

In [10]:
energy_data.isna().sum()

Energy_Source              0
Energy_Consumption(MWh)    0
Cost(Million$)             0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
min_scale = MinMaxScaler()

energy_data["Energy_Consumption(MWh)", ""]

In [11]:
pd.get_dummies(energy_data, columns = ["Energy_Source"])

,Energy_Consumption(MWh),Cost(Million$),Energy_Source_Biomass,Energy_Source_Geothermal,Energy_Source_Hydropower,Energy_Source_Nuclear,Energy_Source_Solar,Energy_Source_Wind
0,2363.0,234.000000,False,True,False,False,False,False
1,1241.0,147.000000,True,False,False,False,False,False
2,2799.4,367.000000,False,False,True,False,False,False
3,3041.0,392.000000,True,False,False,False,False,False
4,3061.0,234.000000,True,False,False,False,False,False
5,2363.0,265.244444,False,False,False,False,False,True
6,3041.0,234.000000,False,False,True,False,False,False
7,3061.0,427.000000,False,False,True,False,False,False
8,3612.0,234.000000,False,False,True,False,False,False
9,3612.0,265.244444,True,False,False,False,False,False
10,2390.0,427.000000,False,True,False,False,False,False
11,3041.0,315.000000,False,False,True,False,False,False
12,3612.0,132.000000,False,False,False,True,False,False
13,3061.0,132.000000,True,False,False,False,False,False
14,2390.0,392.000000,False,False,False,False,False,True
15,3061.0,161.000000,False,True,False,False,False,False
16,2390.0,315.000000,False,False,False,True,False,False
17,3041.0,315.000000,False,False,False,True,False,False
18,2363.0,234.000000,False,False,False,False,False,True
19,3945.0,132.000000,False,True,False,False,False,False
20,3139.0,265.244444,True,False,False,False,False,False
21,2363.0,300.000000,False,False,False,False,True,False
22,3824.0,300.000000,False,True,False,False,False,False
23,3061.0,427.000000,False,False,False,False,False,True
24,3824.0,132.000000,False,False,False,True,False,False
25,2363.0,132.000000,True,False,False,False,False,False
26,2390.0,392.000000,False,True,False,False,False,False
27,3139.0,300.000000,False,False,False,False,True,False
28,3139.0,132.000000,False,False,False,False,True,False
29,2799.4,392.000000,False,False,True,False,False,False
30,3139.0,234.000000,False,False,True,False,False,False
31,3945.0,367.000000,False,False,False,False,False,True
32,3139.0,127.000000,False,True,False,False,False,False
33,2363.0,315.000000,False,True,False,False,False,False
34,2799.4,161.000000,False,False,False,True,False,False
35,2363.0,427.000000,False,False,False,True,False,False
36,2363.0,367.000000,False,False,False,True,False,False
37,2478.0,300.000000,False,False,True,False,False,False
38,1241.0,392.000000,False,True,False,False,False,False
39,2799.4,315.000000,False,True,False,False,False,False
40,2363.0,132.000000,False,False,False,False,True,False
41,1241.0,161.000000,False,False,True,False,False,False
42,1241.0,132.000000,True,False,False,False,False,False
43,2799.4,265.244444,False,False,True,False,False,False
44,2478.0,265.244444,True,False,False,False,False,False
45,3824.0,161.000000,False,False,False,False,True,False
46,2390.0,392.000000,False,False,False,False,False,True
47,3945.0,161.000000,False,True,False,False,False,False
48,2390.0,300.000000,False,False,False,False,True,False
49,3139.0,161.000000,False,True,False,False,False,False